### ISSUE TITLE
Addon not functioning with latest WoTLK update.

### ISSUE THREAD

**Issue by srtzero** [GovtGeek/ShutUpRhonin#5]
Addon seems to have stopped filtering Rhonin while in Dalaran. Issue began with latest WoTLK update v3.4.1.49822

**Comment by GovtGeek** [comment]
Curse picked up a bad version at one point that I eventually removed. Do you have a version listed on this site? You may want to uninstall and reinstall from Curse to see if that was the issue.

(Also, sorry about the close/reopen. My phone didn't like me or github at the time.)

**Comment by srtzero** [comment]
No. Worries. Ok. I did as you said and reinstalled from Curse. Current version showing installed is 3.0.4.1.3.1. I'll check it out and let you know.

**Comment by srtzero** [comment]
Ok. That seems to have worked. No more yell text in chat, and I don't hear him. And I was standing next to him when he was giving his speech. I could see his speech bubble text. So it seems to be working again. Thanks.
